\section[Bayesian Estimation Basics]{Bayesian Estimation Basics\label{ex:BayesianEstimationBasics}}
Consider a simple model:
$$y_t = \mu + u_t$$
with $t = 1, 2,..., T$ and $u_t \sim \mathcal{N}(0,\sigma^2)$.
Assume that $\sigma^2$ is known.
The objective of the econometrician is thus to estimate $\mu$.
\begin{enumerate}
\item How do classical and Bayesian analysis differ?
\item Name the key ingredients for Bayesian estimation.
\item What are \enquote{conjugate priors} and \enquote{natural conjugate priors}?
\end{enumerate}

\paragraph{Readings}
\begin{itemize}
\item \textcite[Part I]{Greenberg_2014_IntroductionBayesianEconometrics}
\item \textcite[Ch.1-2]{Koop_2003_BayesianEconometrics} 
\end{itemize}

\begin{solution}\textbf{Solution to \nameref{ex:BayesianEstimationBasics}}
\ifDisplaySolutions
\input{exercises/bayesian_estimation_basics_solution.inc}
\fi
\newpage
\end{solution}